server:
  port: ${HTTP_PORT:8080}

spring:
  application:
    name: certChecker

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

certificates:
  search:
    path: ${KEYSTORE_PATH:/ssl/certs}


keystore:
  passwords: ${KEYSTORE_PASSWORDS:password1,password2,password3}

logging:
  level:
    ru.alfabank.certChecker: INFO
